speeches = [
    #Caesar BG, 1.2.1-2
    'is m. messāla et p. m. pīsōne cōnsulibus rēgnī cupiditāte inductus conjūrātiōnem nōbilitātis fēcit et cīvitātī persuāsit, ut dē fīnibus suīs cum omnibus cōpiīs exīrent.',
    'perfacile esse, cum virtūte omnibus praestārent, tōtīus galliae imperiō potīrī.',
    #1.3.3-7
    'ad eās rēs cōnficiendās orgetorix dēligitur.',
    'is sibi lēgātiōnem ad cīvitātēs suscēpit.',
    'in eō itinere persuādet castīcō catamantaoedis fīliō sēquanō, cūjus pater rēgnum in sēquanīs multōs annōs obtinuerat et ab senātū populī rōmānī amīcus appellātus erat, ut rēgnum in cīvitāte suā occupāret, quod pater ante habuerat.',
    'itemque dumnorigī haeduō, frātrī dīviciācī, quī eō tempore prīncipātum in cīvitāte obtinēbat ac maximē plēbī acceptus erat, ut īdem cōnārētur persuādet eīque fīliam suam in mātrimōnium dat.',
    'perfacile factū esse illīs probat cōnāta perficere proptereā quod ipse suae cīvitātis imperium obtentūrus esset.',
    'nōn esse dubium, quīn tōtīus galliae plūrimum helvētiī possent.',
    'sē suīs cōpiīs suōque exercit ū illīs rēgna conciliātūrum cōnfirmat.',
    'hāc ōrātiōne adductī inter sē fidem et jūs jūrandum dant et rēgnō occupāt ō per trēs potentissimōs ac firmissimōs populōs tōtīus galliae sēsē potīrī posse spērant.',
    #1.13.3-7
    'is ita cum caesare ēgit.',
    'sī pācem populus rōmānus cum helvētiīs faceret, in eam partem itūrōs atque ibi futūrōs helvētiōs ubi eōs caesar cōnstituisset atque esse voluisset.',
    'sīn bellō persequī persevērāret, reminīscerētur et veteris incommodī populī rōmānī et prīstinae virtūtis helvētiōrum.',
    'quod imprōvīsō ūnum pāgum adortus esset, cum iī quī flūmen trānsīssent, suīs auxilium ferre nōn possent, nē ob eam rem aut suae magnopere virtūtī tribueret aut ipsōs dēspiceret.',
    'sē ita ā patribus mājōribusque suīs didicisse, ut magis virtūte quam dolō contenderent aut īnsidiīs nīterentur.',
    'quārē nē committeret, ut is locus ubi cōnstitissent ex calamitāte populī rōmānī et interneciōne exercitus nōmen caperet aut memoriam prōderet.',
    ##1.14.7
    'divicō respondit.',
    'ita helvētiōs ā mājōribus suīs īnstitūtōs esse utī obsidēs accipere, nōn dare cōnsuērint.',
    'ējus reī populum rōmānum esse testem.',
    #1.44.1-13
    'ariovistus ad postulāta caesaris pauca respondit, dē suīs virtūtibus multa praedicāvit.',
    'trānsīsse rhēnum sēsē nōn suā sponte, sed rogātum et accersītum ā gallīs.',
    'nōn sine magnā spē magnīsque praemiīs domum propinquōsque relīquisse.',
    'sēdēs habēre in galliā ab ipsīs concessās, obsidēs ipsōrum voluntāte datōs.',
    'st īpendium capere jūre bellī, quod victōrēs victīs impōnere cōnsuērint.',
    'nōn sēsē gallīs, sed gallōs sibi bellum intulisse.',
    'omnēs galliae cīvitātēs ad sē oppugnandum vēnisse ac contrā sē castra habuisse.',
    'eās omnēs cōpiās ūnō ā sē proeliō pulsās ac superātās esse.',
    'sī iterum experīrī velint, sē iterum parātum esse dēcertāre.',
    'sī pāce ūtī velint, in īquum esse dē stīpendiō recūsāre, quod suā voluntāte ad id tempus pependerint.',
    'amīcitiam populī rōmānī sibi ōrnāmentō et praesidiō, nōn dētrīmentō esse oportēre, idque sē hāc spē petīsse.',
    'sī per populum rōmānum stīpendium remittātur et dediticiī subtrahantur, nōn minus sē libenter recūsātūrum populī rōmānī amīcitiam quam adpetierit.',
    'quod multitūdinem germānōrum in galliam trādūcat, id sē suī mūniendī, nōn galliae inpugnandae causā facere.',
    'ējus reī testimōnium esse quod nisi rogātus nōn vēnerit et quod bellum nōn intulerit, sed dēfenderit.',
    'sē prius in galliam vēnisse quam populum rōmānum.',
    'numquam ante hōc tempus exercitum populī rōmānī galliae prōvinciae fīnibus ēgressum.',
    'quid sibi vellet.',
    'cūr in suās possessiōnēs venīret.',
    'prōvinciam suam hanc esse galliam, sīcut illam nostram.',
    'ut ipsī concēdī nōn oportēret, sī in nostrōs fīnēs impetum faceret, sīc item nōs esse in īquōs, quod in suō jūre sē interpellārēmus.',
    'quod ā sē haeduōs amīcōs appellātōs dīceret, nōn sē tam barbarum neque tam imperītum esse rērum ut nōn scīret neque bellō allobrogum proximō haeduōs rōmānīs auxilium tulisse, neque ipsōs in hīs contentiōnibus, quās haeduī sēcum et cum sēquanīs habuissent, auxiliō populī rōmānī ūsōs esse.',
    'dēbēre sē suspicārī simulāta caesarem amīcitiā, quod exercitum in galliā habeat, suī opprimendī causā habēre.',
    'quī nisi dēcēdat atque exercitum dēdūcat ex hīs regiōnibus, sēsē illum nōn prō amīcō, sed prō hoste habitūrum.',
    'quodsī eum interfēcerit, multīs sē nōbilibus prīncipibusque populī rōmānī grātum esse factūrum id sē ab ipsīs per eōrum nūntiōs compertum habēre quōrum omnium grātiam atque amīcitiam ējus morte redimere posset.',
    'quodsī dēcessisset et līberam possessiōnem galliae sibi trādidisset, magnō sē illum praemiō remūnerātūrum et quaecumque bella gerī vellet sine ūllō ējus labōre et perīculō cōnfectūrum.',
    #5.7.8
    'ille autem revocātus resistere ac sē manū dēfendere suōrumque fidem implōrāre coepit, saepe clāmitāns līberum sē līberaeque esse cīvitātis.',
    #5.24.4
    'ūnam legiōnem, quam proximē trāns padum cōnscrīpserat, et cohortēs v in eburōnēs, quōrum pars maxima est inter mosam ac rhēnum, quī sub imperiō ambiorigis et catuvolcī erant, mīsit.',
    #5.27.1-11)
    'apud quōs ambiorix ad hunc modum locūtus est.',
    'sēsē prō caesaris in sē beneficiīs plūrimum eī cōnfitērī dēbēre, quod ējus opera stīpendiō līberātus esset, quod atuatucīs fīnitimīs suīs pendēre cōnsuēsset, quodque eī et fīlius et frātris fīlius ā caesare remissī essent, quōs atuatūcī obsidum numerō missōs apud sē in servitūte et catēnīs tenuissent.',
    'neque id quod fēcerit dē oppugnātiōne castrōrum, aut jūdiciō aut voluntāte suā fēcisse, sed coāctū cīvitātis, suaque esse ējusmodī imperia, ut nōn minus habēret jūris in sē multitūdō, quam ipse in multitūdinem.',
    'cīvitātī porrō hanc fuisse bellī causam, quod repentīnae gallōrum conjūrātiōnī resistere nōn potuerit.',
    'id sē facile ex humilitāte suā probāre posse, quod nōn adeō sit imperītus rērum ut suīs cōpiīs populum rōmānum superārī posse cōnfīdat.',
    'sed esse galliae commūne cōnsilium.',
    'omnibus hībernīs caesaris oppugnandīs hunc esse dictum diem, nē quā legiō alterī legiōnī subsidiō venīre posset.',
    'nōn facile gallōs gallīs negāre potuisse, praesertim cum dē recuperandā commūnī lībertāte cōnsilium initum vidērētur.',
    'quibus quoniam prō pietāte satisfēcerit, habēre nunc sē ratiōnem officiī prō beneficiīs caesaris.',
    'monēre, ōrāre titūrium prō hospitiō, ut suae ac mīlitum salūtī cōnsulat.',
    'magnam manum germānōrum conductam rhēnum trānsīsse.',
    'hanc adfore bīduō.',
    'ipsōrum esse cōnsilium, velintne prius, quam fīnitim ī sentiant, ēductōs ex hībernīs mīlitēs aut ad cicerōnem aut ad labiēnum dēdūcere, quōrum alter mīlia passuum circiter quīnquāgintā, alter paulō amplius ab iīs absit.',
    'illud sē pollicērī et jūre jūrandō cōnfirmāre, tūtum iter per suōs fīnēs datūrum.',
    'quod cum faciat, et cīvitātī sēsē cōnsulere, quod hībernīs levētur, et caesarī prō ējus meritīs grātiam referre.',
    'hāc ōrātiōne habitā discēdit ambiorix.',
    #7.1.4-5
    'indictīs inter sē prīncipēs galliae conciliīs silvestribus ac remōtīs locīs queruntur dē accōnis morte.',
    'hunc cāsum ad ipsōs recīdēre posse dēmōnstrant.',
    'miserantur commūnem galliae fortūnam.',
    #7.1.5
    'omnibus pollicitātiōnibus ac praemiīs dēposcunt quī bellī initium faciant et suī capitis perīculō galliam in lībertātem vindicent.',
    #7.1.6-7
    'inprīmīs ratiōnem esse habendam dīcunt, priusquam eōrum clandestīna cōnsilia efferantur, ut caesar ab exercitū interclūdātur.',
    'id esse facile, quod neque legiōnēs audeant absente imperātōre ex hībernīs ēgredī neque imperātor sine praesidiō ad legiōnēs pervenīre possit.',
    #7.1.8
    'postrēmō in aciē praestāre interficī, quam nōn veterem bellī glōriam lībertātemque quam ā mājōribus accēperint recuperāre.',
    #7.14.2-10
    'docet longē aliā ratiōne esse bellum gerendum atque anteā gestum sit.',
    'omnibus modīs huic reī studendum, ut pābulātiōne et commeātū rōmānī prohibeantur.',
    'id esse facile, quod equitātū ipsī abundent et quod annī tempore subleventur.',
    'pābulum secārī nōn posse.',
    'necessāriō dispersōs hostēs ex aedificiīs petere.',
    'hōs omnēs cotīdiē ab equitibus dēlērī posse.',
    'praetereā salūtis causa reī familiāris commoda neglegenda.',
    'vīcōs atque aedificia incendī oportēre hōc spatiō ā boiā quoque versus, quō pābulandī causā adīre posse videantur.',
    'hārum ipsīs rērum cōpiam suppetere, quod quōrum in fīnibus bellum gerātur, eōrum opibus subleventur.',
    'rōmānōs aut inopiam nōn lātūrōs aut magnō cum perīculō longius ā castrīs prōcessūrōs.',
    'neque interesse ipsōsne interficiant impedīmentīsne exuant, quibus āmissīs bellum gerī nōn possit.',
    'praetereā oppida incendī oportēre, quae nōn mūnītiōne et locī nātūrā ab omnī sint perīculō tūta, nē suīs sint ad dētractandam mīlitiam receptācula neu rōmānīs prōposita ad cōpiam commeātus praedamque tollendam.',
    'haec sī gravia aut acerba videantur, multō illa gravius aestimārī dēbēre līberōs conjugēs in servitūtem abstrahī, ipsōs interficī.',
    'quae sit necesse accidere victīs.',
    #7.20.3-7
    'rēgnum illum galliae mālle caesaris concessū quam ipsōrum habēre beneficiō tālī modo accūsātus ad haec respondit.',
    'quod castra mōvisset, factum inopia pābulī etiam ipsīs hortantibus.',
    'quod propius rōmānōs accessisset, persuāsum locī opportūnitāte, quī sē ipse sine mūnītiōne dēfenderet.',
    'equītum vērō operam neque in locō palūstrī dēsīderārī dēbuisse et illīc fuisse ūtilem quō sint profectī.',
    'summam imperiī sē cōnsultō nūllī discēdentem trādidisse, nē is multitūdinis studiō ad dīmicandum impellerētur.',
    'cui reī propter animī mollitiem studēre omnēs vidēret, quod diūtius labōrem ferre nōn possent.',
    'rōmānī sī cāsū intervēnerint, fortūnae, sī alicūjus indiciō vocātī, huic habendam grātiam, quod et paucitātem eōrum ex locō superiōre cognōscere et virtūtem dēspicere potuerint, quī dīmicāre nōn ausī turpiter sē in castra recēperint.',
    'imperium sē ā caesare per prōditiōnem nūllum dēsīderāre quod habēre victōria posset, quae jam esset sibi atque omnibus gallīs explōrāta.',
    'quīn etiam ipsīs remitteret, sī sibi magis honōrem tribuere quam ab sē salūtem accipere videantur.',
    #7.20.8-11)
    'haec ut intellegātis inquit ā mē sincērē prōnūntiārī, audītē rōmānōs mīlitēs.',
    'prōdūcit servōs, quōs in pābulātiōne paucīs ante diēbus excēperat et famē vinculīsque excruciāverat.',
    'hī jam ante ēdoctī quae interrogāt ī prōnūntiārent, mīlitēs sē esse legiōnāriōs dīcunt.',
    'famē atque inopiā adductōs clam ex castrīs exīsse, sī quid frūmentī aut pecoris in agrīs reperīre possent.',
    'similī omnem exercitum inopiā premī nec jam vīrēs sufficere cūjusquam nec ferre operis labōrem posse.',
    'itaque statuisse imperātōrem, sī nihil in oppugnātiōne oppidī prōfēcisset, trīduō exercitum dēdūcere.',
    #7.20.12
    'haec inquit ā mē vercingetorix beneficia habētis, quem prōditiōnis īnsimulātis.',
    'cūjus opera sine vestrō sanguine tantum exercitum victōrem famē paene cōnsūmptum vidētis.',
    'quem turpiter sē ex hāc fugā recipientem nē quā cīvitās suīs fīnibus recipiat, ā mē prōvīsum est.',
    #7.21.1
    'conclāmat omnis multitūdō et suō mōre armīs concrepat, quod facere in eō cōnsuērunt cūjus ōrātiōnem approbant.',
    'summum esse vercingetorigem ducem nec dē ējus fide dubitandum nec mājōre ratiōne bellum administrārī posse.',
    #7.29.1-7
    'posterō diē conciliō convocāt ō cōnsōlātus cohortātusque est, nē sē admodum animō dēmitterent nēve perturbārentur incommodō.',
    'nōn virtūte neque in aciē vīcisse rōmānōs, sed artificiō quōdam et scientia oppugnātiōnis, cūjus reī fuerint ipsī imperītī.',
    'errāre, sī quī in bellō omnēs secundōs rērum prōventūs exspectent.',
    'sibi numquam placuisse avāricum dēfendī, cūjus reī testēs ipsōs habēret, sed factum imprūdentia biturigum et nimia obsequentia reliquōrum, utī hocc incommodum acciperētur.',
    'id tamen sē celeriter mājōribus commodīs sānātūrum.',
    'nam quae ab reliquīs gallīs cīvitātēs dissentīrent, hās suā dīligentiā adjūnctūrum atque ūnum cōnsilium tōtīus galliae effectūrum, cūjus cōnsēnsuī nē orbis quidem terrārum possit obsistere.',
    'idque sē prope jam effectum habēre.',
    'intereā aequum esse ab iīs commūnis salūtis causā impetrārī, ut castra mūnīre īnstituerent, quō facilius repentīnōs hostium impetus sustinēre possent.',
    #(7.37.2-5)
    'cum hīs praemium commūnicat hortāturque ut sē līberōs et imperiō nātōs meminerint.',
    'ūnam esse haeduōrum cīvitātem, quae certissimam galliae victōriam distineat.',
    'ējus auctōritāte reliquās continērī.',
    'quā trāducta locum cōnsistendī rōmānīs in galliā nōn fore.',
    'esse nōnnūllō sē caesaris beneficiō adfectum, sīc tamen, ut jūstissimam apud eum causam obtinuerit.',
    'sed plūs commūnī lībertātī tribuere.',
    'cūr enim potius haeduī dē suō jūre et dē lēgibus ad caesarem disceptātōrem quam rōmānī ad haeduōs veniant.',
    #7.38.1-3
    'litaviccus acceptō exercit ū cum mīlia passuum circiter xxx ā gergoviā abesset, convocātīs subitō mīlitibus lacrimāns quō proficīscimur, inquit mīlitēs.',
    'omnis noster equitātus, omnis nōbilitās interiit.',
    'prīncipēs cīvitātis, eporedorix et viridomarus, īnsimulātī prōditiōnis ab rōmānīs indicta causā interfectī sunt.',
    'haec ab hīs cognōscite, quī ex ipsā caede fūgērunt.',
    'nam ego frātribus atque omnibus meīs propinquīs interfectīs dolōre prohibeor quae gesta sunt prōnūntiāre.',
    #7.38.4-6
    'prōdūcuntur iī, quōs ille ēdocuerat quae dīcī vellet, atque eadem, quae litaviccus prōnūntiāverat, multitūdinī expōnunt.',
    'omnēs equitēs haeduōrum interfectōs, quod conlocūt ī cum arvernīs dīcerentur.',
    'ipsōs sē inter multitūdinem mīlitum occultāsse atque ex mediā caede fūgisse.',
    'conclāmant haeduī et litaviccum obsecrant, ut sibi cōnsulat.',
    #7.38.7-8
    'quasi vērō inquit ille cōnsiliī sit rēs ac nōn necesse sit nōbīs gergoviam contendere et cum arvernīs nōsmet conjungere.',
    'an dubitāmus, quīn nefāriō facinore admissō rōmānī jam ad nōs interficiendōs concurrant.',
    'proinde sī quid in nōbīs animī est, persequāmur eōrum mortem, quī indignissimē interiērunt, atque hōs latrōnēs interficiāmus.',
    #7.77.3-20
    'hicc summō in arvernīs ortus locō et magnae habitūs auctōritātis nihil inquit dē eōrum sententia dictūrus sum, quī turpissimam servitūtem dēditiōnis nōmine appellant, neque hōs habendōs cīvium locō neque ad concilium adhibendōs cēnseō.',
    'cum hīs mihi rēs sit, quī ēruptiōnem probant.',
    'quōrum in cōnsiliō omnium vestrum cōnsēnsū prīstinae residēre virtūtis memoriā vidētur, animī est ista mollitiā, nōn virtūs, paulisper inopiam ferre nōn posse.',
    'quī sē ultrō mortī offerant facilius reperiuntur quam quī dolōrem patienter ferant.',
    'atque ego hanc sententiam probārem tantum apud mē dignitās potest sī nūllam praeterquam vītae nostrae jactūram fierī vidērem.',
    'sed in cōnsiliō capiendō omnem galliam respiciāmus, quam ad nostrum auxilium concitāvimus.',
    'quid hominum mīlibus lxxx ūnō locō interfectīs propinquīs cōnsanguineīsque nostrīs animī fore exīstimātis, sī paene in ipsīs cadāveribus proeliō dēcertāre cōgentur.',
    'nōlīte hōs vestrō auxiliō exspoliāre quī vestrae salūtis causā suum perīculum neglēxērunt, nec stultitiā ac temeritāte vestrā aut animī imbēcillitāte omnem galliam prōsternere et perpetuae servitūtī addīcere.',
    'an quod ad diem nōn vēnērunt, dē eōrum fide cōnstantiāque dubitātis.',
    'quid ergō.',
    'rōmānōs in illīs ulteriōribus mūnītiōnibus animīne causā cotīdiē exercērī putātis.',
    'sī illōrum nūntiīs cōnfirmārī nōn potestis omnī aditū praesaeptō, hīs ūtiminī testibus adpropinquāre eōrum adventum, cūjus reī timōre exterrit ī diem noctemque in opere versantur.',
    'quid ergō meī cōnsiliī est.',
    'facere quod nostrī mājōrēs nēquāquam parī bellō cimbrōrum teutonumque fēcērunt.',
    'quī in oppida compulsī ac similī inopiā subāctī eōrum corporibus, quī aetāte ad bellum inūtilēs vidēbantur, vītam tolerāvērunt neque sē hostibus trādidērunt.',
    'cūjus reī sī exemplum nōn habērēmus, tamen lībertātis causā īnstituī et posterīs prōdī pulcherrimum jūdicārem.',
    'nam quid illī simile bellō fuit.',
    'dēpopulātā galliā cimbrī magnāque inlāta calamitāte fīnibus quidem nostrīs aliquandō excessērunt atque aliās terrās petiērunt.',
    'jūra, lēgēs, agrōs, lībertātem nōbīs relīquērunt.',
    'rōmānī vērō quid petunt aliud aut quid volunt nisi invidiā adductī quōs fāmā nōbilēs potentēsque bellō cognōvērunt, hōrum in agrīs cīvitātibusque cōnsīdere atque hīs aeternam injungere servitūtem.',
    'neque enim umquam aliā condiciōne bella gessērunt.',
    'quodsī ea quae in longinquīs nātiōnibus geruntur ignōrātis, respicite fīnitimam galliam, quae in prōvinciam redācta, jūre et lēgibus commūtātīs, secūribus subjecta perpetuā premitur servitūte.',
    #7.61.1-3
    'ille imperat reliquīs cīvitātibus obsidēs.',
    'dēnique eī reī cōnstituit diem.',
    'hūc omnēs equitēs, xv milia numerō, celeriter convenīre jubet.',
    'peditātū quem anteā habuerit sē fore contentum dīcit neque fortūnam temptātūrum aut aciē dīmicātūrum, sed quoniam abundet equitātū, perfacile esse factū frūmentātiōnibus pābulātiōnibusque rōmānōs prohibēre.',
    'aequō modo animō sua ipsī frūmenta corrumpant aedificiaque incendant, quā reī familiāris jactūra perpetuum imperium lībertātemque sē cōnsequī videant.',
    #7.66.3-6
    'magnō hōrum coactō numerō, cum caesar in sēquanōs per extrēmōs lingonum fīnēs iter faceret, quō facilius subsidium prōvinciae ferre posset, circiter mīlia passuum x ab rōmānīs trīnīs castrīs vercingetorix cōnsēdit convocātīsque ad concilium praefectīs equitum vēnisse tempus victōriae dēmōnstrat.',
    'fugere in prōvinciam rōmānōs galliāque excēdere.',
    'id sibi ad praesentem obtinendam lībertātem satis esse.',
    'ad reliquī temporis pācem atque ōtium parum prōficī.',
    'mājōribus enim coāctīs cōpiīs reversūrōs neque fīnem bellandī factūrōs.',
    'proinde agmine impedītōs adoriantur.',
    'sī peditēs suīs auxilium ferant atque in eō morentur, iter cōnficī nōn posse.',
    'sī id quod magis futūrum cōnfīdat relictīs impedīmentīs suae salūtī cōnsulant, et ūsū rērum necessāriārum et dignitāte spoliātum īrī.',
    'nam dē equitibus hostium, quīn nēmō eōrum prōgredī modo extrā agmen audeat, nē ipsōs quidem dēbēre dubitāre.',
    'id quō mājōre faciant animō, cōpiās sē omnēs prō castrīs habitūrum et terrōrī hostibus futūrum.',
    #7.89.1-2
    'posterō diē vercingetorix conciliō convocāt ō id bellum suscēpisse sē nōn suārum necessitātum, sed commūnis lībertātis causā dēmōnstrat, et quoniam sit fortūnae cēdendum, ad utramque rem sē illīs offerre, seu morte suā rōmānīs satisfacere seu vīvum trādere velint.'
]
